apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-deployment
  namespace: sms-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sms
  template:
    metadata:
      labels:
        app: sms
    spec:
      containers:
        - name: sms
          image: sms-img:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8100
